### ISSUE TITLE
Why does the image have to be "docker-20-04"?

### ISSUE THREAD

**Issue by artis3n** [loft-sh/devpod-provider-digitalocean#2]
DigitalOcean has a [docker-22-04](https://github.com/digitalocean/droplet-1-clicks/tree/master/docker-22-04) 1-click app, but the [only acceptable value](https://github.com/loft-sh/devpod-provider-digitalocean/blob/main/hack/provider/provider.yaml#L53) seems to be `docker-20-04`.

However, `docker-20-04` creates a Docker 23 on Ubuntu 22.04 droplet. Why is that?

**Comment by pascalbreuninger** [comment]
Hi @artis3n, thanks for reporting this issue. That's not the only acceptable value but the default one - feel free to overwrite. 

As to why `docker-20-04` creates the wrong vm, no clue. We'd have to investigate that

**Comment by artis3n** [comment]
Hm, when I change the disk image to `docker-22-04`:

![image](https://github.com/loft-sh/devpod-provider-digitalocean/assets/6969296/1c1aac65-0001-471a-ae0f-e4d88f0afa17)

I get an error from the underlying `doctl` library:

![image](https://github.com/loft-sh/devpod-provider-digitalocean/assets/6969296/9b0a28b2-c664-4fc5-a449-de22ee61258e)

I can use DO's standard image slugs, though:

![image](https://github.com/loft-sh/devpod-provider-digitalocean/assets/6969296/9fb01e6d-3df0-4c43-ac2f-810ba34c7e09)

![image](https://github.com/loft-sh/devpod-provider-digitalocean/assets/6969296/095d3414-fce2-48ee-947b-14b877c0e85d)


When `docker-20-04` is set, a [Docker 1-click app](https://marketplace.digitalocean.com/apps/docker) is used to set up the Droplet, while using a regular DO slug creates a "standard" DO droplet and installs docker-ce inside it after the devpod agent comes up.

My original issue was me trying to specify the `docker-22-04` 1-click docker app, which does not work. But a regular DO slug does work fine. It is interesting that `docker-20-04` works at all and leverages the marketplace app. I wonder if the default image type option for the DO provider should instead be `ubuntu-20-04-x64` or (preferably) `ubuntu-22-04-x64` instead of `docker-20-04`.

**Comment by 89luca89** [comment]
Hi @artis3n 

Following the DO's API docs, the `docker-20-04` slug corresponds to `Docker 23.0.6 on Ubuntu 22.04` as reported here: https://slugs.do-api.dev/ in the "App Images" tab

![image](https://github.com/loft-sh/devpod-provider-digitalocean/assets/598882/3bd8f700-6bfb-4778-b51c-6adaf0e67be7)

So it does not HAVE TO be `docker-20-04` it can be others, and I'll add a proper suggesion list to the provider now
But the confusing part is that the slug indicates 20-04 and it puts docker 23 and ubuntu 22 :joy:  but that's DO's API thing, not DevPod.

As stated, I'll add a proper suggestion list (keeping the docker droplet as default)

**Comment by artis3n** [comment]
Ha, who can say. Great fix, thanks!
